#ifndef PARAMS_H
#define PARAMS_H

#ifndef OSKR_K
#define OSKR_K 2	/* Change this for different security strengths */
#endif

#ifndef OSKR_N
#define OSKR_N 256
#endif

#define OSKR_Q 3329

#if (FO == 1)
#define CCS21
#endif

#if (OSKR_N == 256)
#define OSKR_SYMBYTES 32   /* size in bytes of hashes, and seeds */
#define OSKR_SSBYTES  32   /* size in bytes of shared key */
#define OSKR_POLYBYTES		384
#if OSKR_K == 2
#define OSKR_ETA1 3
#define OSKR_POLYCOMPRESSEDBYTES    128
#define OSKR_POLYVECCOMPRESSEDBYTES (OSKR_K * 320)
#elif OSKR_K == 3
#define OSKR_ETA1 2
#define OSKR_POLYCOMPRESSEDBYTES    128
#define OSKR_POLYVECCOMPRESSEDBYTES (OSKR_K * 320)
#endif
#elif (OSKR_N == 512)
#define OSKR_ETA1 2
#define OSKR_SYMBYTES 64
#define OSKR_SSBYTES  64
#define OSKR_POLYBYTES		384*2
#define OSKR_POLYCOMPRESSEDBYTES    160*2
#define OSKR_POLYVECCOMPRESSEDBYTES (OSKR_K * 352 * 2)
#endif

#define OSKR_ETA2 2

#define OSKR_POLYVECBYTES	(OSKR_K * OSKR_POLYBYTES)

#define OSKR_INDCPA_MSGBYTES       (OSKR_SYMBYTES)
#define OSKR_INDCPA_PUBLICKEYBYTES (OSKR_POLYVECBYTES + OSKR_SYMBYTES)
#define OSKR_INDCPA_SECRETKEYBYTES (OSKR_POLYVECBYTES)
#define OSKR_INDCPA_BYTES          (OSKR_POLYVECCOMPRESSEDBYTES + OSKR_POLYCOMPRESSEDBYTES)

#define OSKR_PUBLICKEYBYTES  (OSKR_INDCPA_PUBLICKEYBYTES)

#define OSKR_SECRETKEYBYTES  (OSKR_INDCPA_SECRETKEYBYTES + OSKR_INDCPA_PUBLICKEYBYTES + 2*OSKR_SYMBYTES)
#define OSKR_CIPHERTEXTBYTES (OSKR_INDCPA_BYTES)

#endif
