#ifndef PARAMS_H
#define PARAMS_H

#ifndef OKAI_K
#define OKAI_K 2	/* Change this for different security strengths */
#endif

#ifndef OKAI_N
#define OKAI_N 256
#endif

#if (FO == 1)
#define CCS21
#endif

#define OKAI_Q 7681

#if (OKAI_N == 256)
#define OKAI_SYMBYTES 32
#define OKAI_POLYBYTES	416
#define OKAI_SETA 1
#define OKAI_EETA 4
#if OKAI_K == 2
#define OKAI_POLYCOMPRESSEDBYTES    128
#define OKAI_POLYVECCOMPRESSEDPKBYTES (OKAI_K * 288)
#define OKAI_POLYVECCOMPRESSEDCBYTES  (OKAI_K * 256)
#elif OKAI_K == 3
#define OKAI_POLYCOMPRESSEDBYTES    128
#define OKAI_POLYVECCOMPRESSEDPKBYTES (OKAI_K * 288)
#define OKAI_POLYVECCOMPRESSEDCBYTES  (OKAI_K * 288)
#endif
#elif (OKAI_N == 512)
#define OKAI_SYMBYTES 64
#define OKAI_POLYBYTES              416 * 2
#define OKAI_SETA 1
#define OKAI_EETA 6
#define OKAI_POLYCOMPRESSEDBYTES    128 * 2
#define OKAI_POLYVECCOMPRESSEDPKBYTES (OKAI_K * 320 * 2)
#define OKAI_POLYVECCOMPRESSEDCBYTES  (OKAI_K * 320 * 2)
#endif

#define OKAI_POLYVECBYTES           (OKAI_K * OKAI_POLYBYTES)

#define OKAI_INDCPA_MSGBYTES       OKAI_SYMBYTES
#define OKAI_INDCPA_PUBLICKEYBYTES (OKAI_POLYVECCOMPRESSEDPKBYTES + OKAI_SYMBYTES)
#define OKAI_INDCPA_SECRETKEYBYTES (OKAI_POLYVECBYTES)
#define OKAI_INDCPA_BYTES          (OKAI_POLYVECCOMPRESSEDCBYTES + OKAI_POLYCOMPRESSEDBYTES)

#define OKAI_PUBLICKEYBYTES  (OKAI_INDCPA_PUBLICKEYBYTES)
#define OKAI_SECRETKEYBYTES  (OKAI_INDCPA_SECRETKEYBYTES +  OKAI_INDCPA_PUBLICKEYBYTES + 2*OKAI_SYMBYTES) /* 32 bytes of additional space to save H(pk) */
#define OKAI_CIPHERTEXTBYTES  OKAI_INDCPA_BYTES

#endif
